import type { Metadata } from "next";
import { Inter, Lato, Aleo } from "next/font/google";
import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--inter"
});

const lato = Lato({ 
  subsets: ["latin"], 
  variable: "--lato",
  weight: ["400", "700"]
});

const aleo = Aleo({ 
  subsets: ["latin"], 
  variable: "--aleo",
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lato.variable} ${aleo.variable}`}>{children}</body>
    </html>
  );
}
